######################################################################
# Automatically generated by qmake (3.0) ven. janv. 17 14:46:54 2014
######################################################################

TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS = main tests

main.file = main.pro
main.depends =
tests.file = tests/tests.pro
tests.depends = main

DISTFILES += \
    README.md \
    clemanglaise.rc

android: include($$ANDROID_SSL_LIBS/openssl.pri)
